server:
  port: 8081

spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .html

  datasource:
    url: jdbc:mysql://localhost:3306/vue_boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: cn.luoqikun.vue_boot.entity
  configuration.map-underscore-to-camel-case: true
  #配置在控制台打印sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




redis:
  host: 127.0.0.1
  port: 6379
  password:





